spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/manager?user=root&password=root
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  activemq:
    broker-url: tcp://localhost:61616
  jms:
    pub-sub-domain: true

server:
  context-path: /manager
  port: 8081
logging:
  level:
   com.zq.manager: debug